<?php

namespace frontend\filters;

use common\models\Advert;
use Yii;
use yii\base\ActionFilter;
use yii\web\HttpException;

class FilterAdvert extends ActionFilter
{
    public function beforeAction($action)
    {

        $id = Yii::$app->request->get('id');
        $model = Advert::findOne($id);


        if ($model == null) {
            throw new HttpException(404, "Not found any advert");
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}